# Service to make your Java app accessible from outside
apiVersion: v1
kind: Service
metadata:
  name: book-service
  labels:
    app: book-service
spec:
  type: LoadBalancer  # Makes app accessible from outside Kubernetes
  ports:
  - port: 80          # External port
    targetPort: 8080  # Internal port (where your app runs)
    protocol: TCP
    name: http
  selector:
    app: book-service
